### ISSUE TITLE
Issues with issues?

### ISSUE THREAD

**Issue by comradekingu** [stackshareio/dev-tools-for-blm#2]
@stackshareio can lock issues, for no other reason than supposedly being "too heated".
I would like this policy explained. In my view you could allow factual information and discussion, as opposed to only advertising.

Before that @johnnyxbell closed issue #1 which is maybe neither here nor there.

The makeshift website this repo links to says:

>Ways You Can Help
When You’re Done: Educate Yourself. This Doesn’t Go Away Once The Topic Isn’t, “Trending.”

Edit: I noticed this is actually a stackshareio initiative.

StackShare uses its own platform to forward issues not directly related to it (from what I can tell). This is from an e-mail I got today:

>Dear StackShare Community,
 
>George Floyd, Ahmaud Arbery, and Breonna Taylor all died from the same disease: racism. The culture of white supremacy and police brutality that led to their murders is undeniable and people all across the US, including myself, are angry, frustrated, and grieving. Unfortunately, the list of black men and women who have died for no other reason than the color of their skin, goes on and on, and will continue to grow if we all don't do something about it.

I don't support racism, and hope the distinction between using it and fighting it is maybe made clear by the above quote.

I was editing my post in issue #1 to say something along the lines of: "In my view BLM is deceptive in their presentation of present societal issues, and their narrative of them" to @The-Don-Himself before it got locked.

Even without that part, consequently, how is anyone supposed to educate themselves (like suggested) without discussing presented info, (or the lack thereof) and seeking out and sharing educational material?

If I am misinformed, I don't want to be, and expect others to bring matters to light in the interest of the disabuse one could wish for others, in the same way I am. If I am out of line just tell me by explaining how, and possibly include ideas for improvement.

From https://help.github.com/en/github/site-policy/github-community-guidelines
>We encourage active participation in the expression of ideas, perspectives, and experiences and may not be in a position to dispute personal accounts or observations.

**Comment by yonasb** [comment]
@comradekingu hi, I created this repo. I'm not clear on exactly what you're asking for here. Are you saying that you'd simply like the ability to express your dislike of this repo via GH Issues here? Or are you asking for more info?

**Comment by antenore** [comment]
@yonasb the point is that someone (@comradekingu , @alex20465 and now me) have reported an issue with the way Github is supposed to be used, but instead of allowing a friendly and positive discussion, you locked #1  .

Beside the reasons to complain, that I share, you cannot just lock an issue because you don't agree with what people have to say, this is not how Github is meant to be used. 

Now you can lock also this issue if you wish.

**Comment by yonasb** [comment]
@antenore disagree with that. The original point from the first issue, was that people disagreed with the existence of the repo. That was not a positive and friendly discussion they were interested in having (the original issue didn't even have a description, just a title which was not helpful).

Regarding the use of GitHub: neither you nor the original comment author work for GitHub so you don't actually have the authority to decide whether or not this is the correct use of GitHub or not. You can comment on it, sure. That doesn't mean that we have to entertain your comments though. There is no specific guidance that says we cannot lock an issue when we feel as though the conversation is not constructive.

Have a nice day (and thank you for giving us permission to lock this issue!).
